/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package standarapp.gui;

import javax.swing.JLabel;

/**
 *
 * @author Niki
 */
public class ParticularSearch extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public ParticularSearch() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimizeButton = new javax.swing.JButton();
        labelTittle = new javax.swing.JLabel();
        derechosLabel = new javax.swing.JLabel();
        derechosEmailLabel = new javax.swing.JLabel();
        municipioLabel = new javax.swing.JLabel();
        municipioTextField = new javax.swing.JTextField();
        departamentoLabel = new javax.swing.JLabel();
        departamentoTextField = new javax.swing.JTextField();
        localidadLabel = new javax.swing.JLabel();
        localidadTextField = new javax.swing.JTextField();
        codigoLabel = new javax.swing.JLabel();
        codigoTextField = new javax.swing.JTextField();
        answerPanel = new javax.swing.JScrollPane();
        answerTextArea = new javax.swing.JTextArea();
        doButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeButton.setBackground(new java.awt.Color(0, 153, 153));
        minimizeButton.setFont(new java.awt.Font("Adobe Arabic", 0, 3)); // NOI18N
        minimizeButton.setForeground(new java.awt.Color(255, 255, 255));
        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize.png"))); // NOI18N
        minimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(minimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 20, 20));

        labelTittle.setBackground(new java.awt.Color(79, 152, 43));
        labelTittle.setFont(new java.awt.Font("Gill Sans MT", 0, 28)); // NOI18N
        labelTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTittle.setText("StandarApp 1.0");
        getContentPane().add(labelTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 540, 40));

        derechosLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        derechosLabel.setForeground(new java.awt.Color(153, 153, 153));
        derechosLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        derechosLabel.setText("Designed by Nicolas Ordoñez Chala, 2017");
        getContentPane().add(derechosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 260, 20));

        derechosEmailLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        derechosEmailLabel.setForeground(new java.awt.Color(153, 153, 153));
        derechosEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        derechosEmailLabel.setText("info: nordonezc@unal.edu.co");
        getContentPane().add(derechosEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 260, 20));

        municipioLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        municipioLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        municipioLabel.setText("Municipio:");
        getContentPane().add(municipioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 30));

        municipioTextField.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        municipioTextField.setText("Ingrese un nombre de un municipio");
        municipioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipioTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(municipioTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 220, 30));

        departamentoLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        departamentoLabel.setText("Departamento:");
        getContentPane().add(departamentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, 30));

        departamentoTextField.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        departamentoTextField.setText("Ingrese un nombre de departamento");
        departamentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(departamentoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 220, 30));

        localidadLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        localidadLabel.setText("Localidad:");
        getContentPane().add(localidadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 100, 30));

        localidadTextField.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        localidadTextField.setText("Ingrese un nombre de Localidad");
        localidadTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localidadTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(localidadTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 220, 30));

        codigoLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        codigoLabel.setText("Codigo:");
        getContentPane().add(codigoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 100, 30));

        codigoTextField.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        codigoTextField.setText("Ingrese un codigo de localidad");
        getContentPane().add(codigoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 220, 30));

        answerPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        answerPanel.setFocusable(false);

        answerTextArea.setColumns(20);
        answerTextArea.setLineWrap(true);
        answerTextArea.setRows(5);
        answerTextArea.setText("Resultado:\nIngrese texto \nen el campo \npor el cual \ndesea buscar\ny luego \npresione el \nboton\nbúscar.");
        answerTextArea.setWrapStyleWord(true);
        answerTextArea.setDragEnabled(true);
        answerPanel.setViewportView(answerTextArea);

        getContentPane().add(answerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 170, 150));

        doButton.setBackground(new java.awt.Color(0, 153, 153));
        doButton.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        doButton.setForeground(new java.awt.Color(255, 255, 255));
        doButton.setText("Buscar");
        doButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doButtonActionPerformed(evt);
            }
        });
        getContentPane().add(doButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 110, -1));

        backButton.setBackground(new java.awt.Color(0, 153, 153));
        backButton.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Regresar");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 110, -1));

        exitButton.setBackground(new java.awt.Color(204, 51, 0));
        exitButton.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        exitButton.setText("Salir");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 70, -1));

        backgroundLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/greenPolygons.jpg"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void localidadTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localidadTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localidadTextFieldActionPerformed

    private void departamentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departamentoTextFieldActionPerformed

    private void minimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeButtonActionPerformed
        // TODO add your handling code here:
        setState(this.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonActionPerformed

    private void municipioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipioTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParticularSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParticularSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParticularSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParticularSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParticularSearch().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane answerPanel;
    private javax.swing.JTextArea answerTextArea;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoTextField;
    private javax.swing.JLabel departamentoLabel;
    private javax.swing.JTextField departamentoTextField;
    private javax.swing.JLabel derechosEmailLabel;
    private javax.swing.JLabel derechosLabel;
    private javax.swing.JButton doButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel labelTittle;
    private javax.swing.JLabel localidadLabel;
    private javax.swing.JTextField localidadTextField;
    private javax.swing.JButton minimizeButton;
    private javax.swing.JLabel municipioLabel;
    private javax.swing.JTextField municipioTextField;
    // End of variables declaration//GEN-END:variables
}
