/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package standarapp.gui;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;
import standarapp.algorithm.Lecture;
import standarapp.algorithm.ReadRegistry;

/**
 *
 * @author Niki
 */
public class ReadCases extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    private ReadRegistry rr;
    /**
     * Creates new form Menu
     */
    public ReadCases(int x, int y, String nameExcel) throws IOException {
        initComponents();
        this.setLocation(x, y);
        this.setIconImage(new ImageIcon(getClass().getResource("/images/SPicon.png")).getImage());
        this.setTitle("StandarApp");
        rr = new ReadRegistry(nameExcel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimizeButton = new javax.swing.JButton();
        labelTittle = new javax.swing.JLabel();
        instructionOne = new javax.swing.JLabel();
        instructionOne1 = new javax.swing.JLabel();
        inFileTextField = new javax.swing.JTextField();
        inFileButton = new javax.swing.JButton();
        cod_dpto_o_label = new javax.swing.JLabel();
        cod_dpto_o_textField = new javax.swing.JTextField();
        cod_mun_o_label = new javax.swing.JLabel();
        cod_mun_o_textField = new javax.swing.JTextField();
        localidad_label = new javax.swing.JLabel();
        localidad_textField = new javax.swing.JTextField();
        cen_pobla_label = new javax.swing.JLabel();
        cen_pobla_textField = new javax.swing.JTextField();
        dir_res_label = new javax.swing.JLabel();
        dir_res_textField = new javax.swing.JTextField();
        vereda_label = new javax.swing.JLabel();
        vereda_textField = new javax.swing.JTextField();
        bar_ver_label = new javax.swing.JLabel();
        bar_ver_textField = new javax.swing.JTextField();
        nmun_proce_label = new javax.swing.JLabel();
        nmun_proce_textField = new javax.swing.JTextField();
        nmun_resi_label = new javax.swing.JLabel();
        nmun_resi = new javax.swing.JTextField();
        instructionThree = new javax.swing.JLabel();
        pagesTextField = new javax.swing.JTextField();
        OmitLabelTwo = new javax.swing.JLabel();
        instructionFour = new javax.swing.JLabel();
        percentTextField = new javax.swing.JTextField();
        percentThree = new javax.swing.JLabel();
        instructionFive = new javax.swing.JLabel();
        outFileTextField = new javax.swing.JTextField();
        outFileButton = new javax.swing.JButton();
        omitLabelThree = new javax.swing.JLabel();
        answerLabel = new javax.swing.JLabel();
        doButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        derechosLabel = new javax.swing.JLabel();
        derechosEmailLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        dragLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeButton.setBackground(new java.awt.Color(0, 153, 153));
        minimizeButton.setFont(new java.awt.Font("Adobe Arabic", 0, 3)); // NOI18N
        minimizeButton.setForeground(new java.awt.Color(255, 255, 255));
        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize.png"))); // NOI18N
        minimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(minimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 20, 20));

        labelTittle.setBackground(new java.awt.Color(79, 152, 43));
        labelTittle.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        labelTittle.setText("StandarApp 3.0");
        getContentPane().add(labelTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 250, 40));

        instructionOne.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        instructionOne.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        instructionOne.setText("diligenciados en la ficha de reporte");
        getContentPane().add(instructionOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        instructionOne1.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        instructionOne1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        instructionOne1.setText("Indique la ruta del archivo(solo xlsx) que contiene los datos de enfermedades");
        getContentPane().add(instructionOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 20));

        inFileTextField.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        inFileTextField.setText("Dirección del archivo de entrada...");
        getContentPane().add(inFileTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 410, 30));

        inFileButton.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        inFileButton.setText("...");
        inFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inFileButtonActionPerformed(evt);
            }
        });
        getContentPane().add(inFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 40, 30));

        cod_dpto_o_label.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        cod_dpto_o_label.setText("cod Dpto");
        getContentPane().add(cod_dpto_o_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 80, 30));

        cod_dpto_o_textField.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        cod_dpto_o_textField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cod_dpto_o_textField.setText("16");
        cod_dpto_o_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod_dpto_o_textFieldActionPerformed(evt);
            }
        });
        getContentPane().add(cod_dpto_o_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 30, 30));

        cod_mun_o_label.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        cod_mun_o_label.setText("cod Municipio");
        getContentPane().add(cod_mun_o_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 80, 30));

        cod_mun_o_textField.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        cod_mun_o_textField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cod_mun_o_textField.setText("17");
        cod_mun_o_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod_mun_o_textFieldActionPerformed(evt);
            }
        });
        getContentPane().add(cod_mun_o_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 30, 30));

        localidad_label.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        localidad_label.setText("localidad");
        getContentPane().add(localidad_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 80, 30));

        localidad_textField.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        localidad_textField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        localidad_textField.setText("19");
        localidad_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localidad_textFieldActionPerformed(evt);
            }
        });
        getContentPane().add(localidad_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 30, 30));

        cen_pobla_label.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        cen_pobla_label.setText("Centro poblado");
        getContentPane().add(cen_pobla_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 100, 30));

        cen_pobla_textField.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        cen_pobla_textField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cen_pobla_textField.setText("20");
        cen_pobla_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cen_pobla_textFieldActionPerformed(evt);
            }
        });
        getContentPane().add(cen_pobla_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 30, 30));

        dir_res_label.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        dir_res_label.setText("Direccion residencia");
        getContentPane().add(dir_res_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 120, 30));

        dir_res_textField.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        dir_res_textField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dir_res_textField.setText("23");
        dir_res_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dir_res_textFieldActionPerformed(evt);
            }
        });
        getContentPane().add(dir_res_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 30, 30));

        vereda_label.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        vereda_label.setText("Vereda");
        getContentPane().add(vereda_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 80, 30));

        vereda_textField.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        vereda_textField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vereda_textField.setText("21");
        vereda_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vereda_textFieldActionPerformed(evt);
            }
        });
        getContentPane().add(vereda_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 30, 30));

        bar_ver_label.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        bar_ver_label.setText("Barrio vereda");
        getContentPane().add(bar_ver_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 100, 30));

        bar_ver_textField.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        bar_ver_textField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bar_ver_textField.setText("22");
        bar_ver_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bar_ver_textFieldActionPerformed(evt);
            }
        });
        getContentPane().add(bar_ver_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 30, 30));

        nmun_proce_label.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        nmun_proce_label.setText("Municipio procedencia");
        getContentPane().add(nmun_proce_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 130, 30));

        nmun_proce_textField.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        nmun_proce_textField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nmun_proce_textField.setText("96");
        nmun_proce_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmun_proce_textFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nmun_proce_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 30, 30));

        nmun_resi_label.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        nmun_resi_label.setText("Municipio residencia");
        getContentPane().add(nmun_resi_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 130, 30));

        nmun_resi.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        nmun_resi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nmun_resi.setText("98");
        nmun_resi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmun_resiActionPerformed(evt);
            }
        });
        getContentPane().add(nmun_resi, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 30, 30));

        instructionThree.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        instructionThree.setText("Ingrese numero de pagina:");
        getContentPane().add(instructionThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 160, 30));

        pagesTextField.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        pagesTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pagesTextField.setText("0");
        pagesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagesTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(pagesTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 30, 30));

        OmitLabelTwo.setFont(new java.awt.Font("Lao UI", 0, 10)); // NOI18N
        OmitLabelTwo.setForeground(new java.awt.Color(51, 51, 51));
        OmitLabelTwo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        OmitLabelTwo.setText("(Omitir, en caso de no conocer)");
        getContentPane().add(OmitLabelTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 150, 20));

        instructionFour.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        instructionFour.setText("Porcentaje comparación localidad: ");
        getContentPane().add(instructionFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 190, 30));

        percentTextField.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        percentTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        percentTextField.setText("80");
        percentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(percentTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 40, 30));

        percentThree.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        percentThree.setText("%");
        getContentPane().add(percentThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 10, 30));

        instructionFive.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        instructionFive.setText("Indique la ruta donde desea guardar el archivo de salida");
        getContentPane().add(instructionFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 450, 20));

        outFileTextField.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        outFileTextField.setText("Ubicación para el archivo de salida...");
        getContentPane().add(outFileTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 410, 30));

        outFileButton.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        outFileButton.setText("...");
        outFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outFileButtonActionPerformed(evt);
            }
        });
        getContentPane().add(outFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 40, 30));

        omitLabelThree.setFont(new java.awt.Font("Lao UI", 0, 10)); // NOI18N
        omitLabelThree.setForeground(new java.awt.Color(51, 51, 51));
        omitLabelThree.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        omitLabelThree.setText("(Si desea sobreescribir el archivo de entrada,  ignore este paso, y presione arreglar)");
        getContentPane().add(omitLabelThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        answerLabel.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        answerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerLabel.setText("Presione arreglar para continuar");
        getContentPane().add(answerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 430, 20));

        doButton.setBackground(new java.awt.Color(0, 153, 153));
        doButton.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        doButton.setForeground(new java.awt.Color(255, 255, 255));
        doButton.setText("Arreglar");
        doButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doButtonActionPerformed(evt);
            }
        });
        getContentPane().add(doButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 130, -1));

        backButton.setBackground(new java.awt.Color(0, 153, 153));
        backButton.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Regresar");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 140, -1));

        exitButton.setBackground(new java.awt.Color(204, 51, 0));
        exitButton.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        exitButton.setText("Salir");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 110, -1));

        derechosLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        derechosLabel.setForeground(new java.awt.Color(153, 153, 153));
        derechosLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        derechosLabel.setText("Designed by Nicolas Ordoñez Chala, 2017");
        getContentPane().add(derechosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 260, 20));

        derechosEmailLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        derechosEmailLabel.setForeground(new java.awt.Color(153, 153, 153));
        derechosEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        derechosEmailLabel.setText("info: nordonezc@unal.edu.co");
        getContentPane().add(derechosEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 260, 20));

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SPicon.png"))); // NOI18N
        getContentPane().add(iconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, 40));

        dragLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragLabelMouseDragged(evt);
            }
        });
        dragLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragLabelMousePressed(evt);
            }
        });
        getContentPane().add(dragLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 530, 500));

        backgroundLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/greenPolygons.jpg"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doButtonActionPerformed
        // TODO add your handling code here:
        String nameIn = inFileTextField.getText();
        String nameOut = outFileTextField.getText();
        String collumns = cod_dpto_o_textField.getText();
        double percent = Double.valueOf(percentTextField.getText());
        int number1 = Integer.valueOf(cod_dpto_o_textField.getText());
        int number2 = Integer.valueOf(cod_mun_o_textField.getText());
        int number3 = Integer.valueOf(localidad_textField.getText());
        int number4 = Integer.valueOf(cen_pobla_textField.getText());
        int number5 = Integer.valueOf(vereda_textField.getText());
        int number6 = Integer.valueOf(bar_ver_textField.getText());
        int number7 = Integer.valueOf(dir_res_textField.getText());
        int number8 = Integer.valueOf(nmun_proce_textField.getText());
        int number9 = Integer.valueOf(nmun_resi.getText());
        
        int[] col = {number1,number2,number3,number4,number5,number6,number7,number8,number9};
        
        double pages = Double.valueOf(pagesTextField.getText());

        try {
            if (!nameIn.contains("...")) {
                if (nameOut.contains("...")) {
                    String answer = rr.lectureRegistry(nameIn, nameIn, col, percent);
                    answerLabel.setForeground(Color.BLUE);
                    answerLabel.setText(answer + nameIn);

                } else if (Lecture.determineExtensionFile(nameIn)) {
                    String answer = rr.lectureRegistry(nameIn, nameOut + "\\standarizedRegistries.xlsx", col, percent);
                    answerLabel.setForeground(Color.BLUE);
                    answerLabel.setText(answer + " en: " + nameOut + "\\standarizedRegistries.xlsx");
                } else {
                    String answer = rr.lectureRegistry(nameIn, nameOut + "\\standarizedRegistries.xls", col, percent);
                    answerLabel.setForeground(Color.BLUE);
                    answerLabel.setText(answer + " en: " + nameOut + "\\fixedFile.xls");
                }
            } else {
                answerLabel.setForeground(Color.red);
                answerLabel.setText("No ha seleccionado ningun archivo");
            }
        } catch (Exception e) {
            answerLabel.setForeground(Color.red);
            answerLabel.setText("Revisar los campos de seleccion de archivos");
        }
    }//GEN-LAST:event_doButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu windowTwo = new Menu(this.getX(), this.getY());
        windowTwo.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void cod_dpto_o_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod_dpto_o_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cod_dpto_o_textFieldActionPerformed

    private void minimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeButtonActionPerformed
        // TODO add your handling code here:
        setState(this.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonActionPerformed

    private void pagesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagesTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagesTextFieldActionPerformed

    private void percentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_percentTextFieldActionPerformed

    private void dragLabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragLabelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_dragLabelMouseDragged

    private void dragLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragLabelMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_dragLabelMousePressed

    private void inFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inFileButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setFileFilter(new FileNameExtensionFilter("Excel Files",  "xlsx"));
        //chooser.addChoosableFileFilter(new FileNameExtensionFilter("xls Files", "xls"));
        //chooser.addChoosableFileFilter(new FileNameExtensionFilter("xlsx Files", "xlsx"));
        chooser.setAcceptAllFileFilterUsed(false);
        
        int option = chooser.showOpenDialog(this);
        if (JFileChooser.CANCEL_OPTION == option) 
            inFileTextField.setText("No ha seleccionado ningun archivo...");
        
        if (JFileChooser.APPROVE_OPTION == option) 
            inFileTextField.setText(chooser.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_inFileButtonActionPerformed

    private void outFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outFileButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        int option = chooser.showSaveDialog(this);
        if (JFileChooser.APPROVE_OPTION == option) 
            outFileTextField.setText("No ha seleccionado ninguna ubicación...");
        
        if (JFileChooser.APPROVE_OPTION == option) 
            outFileTextField.setText(chooser.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_outFileButtonActionPerformed

    private void cod_mun_o_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod_mun_o_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cod_mun_o_textFieldActionPerformed

    private void localidad_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localidad_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localidad_textFieldActionPerformed

    private void cen_pobla_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cen_pobla_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cen_pobla_textFieldActionPerformed

    private void dir_res_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dir_res_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dir_res_textFieldActionPerformed

    private void vereda_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vereda_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vereda_textFieldActionPerformed

    private void bar_ver_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bar_ver_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bar_ver_textFieldActionPerformed

    private void nmun_proce_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmun_proce_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmun_proce_textFieldActionPerformed

    private void nmun_resiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmun_resiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmun_resiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OmitLabelTwo;
    private javax.swing.JLabel answerLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel bar_ver_label;
    private javax.swing.JTextField bar_ver_textField;
    private javax.swing.JLabel cen_pobla_label;
    private javax.swing.JTextField cen_pobla_textField;
    private javax.swing.JLabel cod_dpto_o_label;
    private javax.swing.JTextField cod_dpto_o_textField;
    private javax.swing.JLabel cod_mun_o_label;
    private javax.swing.JTextField cod_mun_o_textField;
    private javax.swing.JLabel derechosEmailLabel;
    private javax.swing.JLabel derechosLabel;
    private javax.swing.JLabel dir_res_label;
    private javax.swing.JTextField dir_res_textField;
    private javax.swing.JButton doButton;
    private javax.swing.JLabel dragLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JButton inFileButton;
    private javax.swing.JTextField inFileTextField;
    private javax.swing.JLabel instructionFive;
    private javax.swing.JLabel instructionFour;
    private javax.swing.JLabel instructionOne;
    private javax.swing.JLabel instructionOne1;
    private javax.swing.JLabel instructionThree;
    private javax.swing.JLabel labelTittle;
    private javax.swing.JLabel localidad_label;
    private javax.swing.JTextField localidad_textField;
    private javax.swing.JButton minimizeButton;
    private javax.swing.JLabel nmun_proce_label;
    private javax.swing.JTextField nmun_proce_textField;
    private javax.swing.JTextField nmun_resi;
    private javax.swing.JLabel nmun_resi_label;
    private javax.swing.JLabel omitLabelThree;
    private javax.swing.JButton outFileButton;
    private javax.swing.JTextField outFileTextField;
    private javax.swing.JTextField pagesTextField;
    private javax.swing.JTextField percentTextField;
    private javax.swing.JLabel percentThree;
    private javax.swing.JLabel vereda_label;
    private javax.swing.JTextField vereda_textField;
    // End of variables declaration//GEN-END:variables
}
