/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package standarapp.gui;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;
import standarapp.algorithm.Lecture;
import standarapp.algorithm.ReadRegistry;

/**
 *
 * @author Niki
 */
public class ReadVectors extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    private ReadRegistry rr;
    /**
     * Creates new form Menu
     */
    public ReadVectors(int x, int y, String nameExcel) throws IOException {
        initComponents();
        this.setLocation(x, y);
        this.setIconImage(new ImageIcon(getClass().getResource("/images/SPicon.png")).getImage());
        this.setTitle("StandarApp");
        rr = new ReadRegistry(nameExcel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimizeButton = new javax.swing.JButton();
        labelTittle = new javax.swing.JLabel();
        instructionOne = new javax.swing.JLabel();
        inFileTextField = new javax.swing.JTextField();
        inFileButton = new javax.swing.JButton();
        filaEncabezado1Label = new javax.swing.JLabel();
        filaEncabezado2Label = new javax.swing.JLabel();
        fila_textField = new javax.swing.JTextField();
        especieLabel = new javax.swing.JLabel();
        especie_textField = new javax.swing.JTextField();
        localidadLabel = new javax.swing.JLabel();
        localidad_textField = new javax.swing.JTextField();
        fechaLabel = new javax.swing.JLabel();
        fecha_textField = new javax.swing.JTextField();
        municipioLabel = new javax.swing.JLabel();
        municipio_textField = new javax.swing.JTextField();
        instructionFive = new javax.swing.JLabel();
        outFileTextField = new javax.swing.JTextField();
        outFileButton = new javax.swing.JButton();
        omitLabelThree = new javax.swing.JLabel();
        omitLabelThree1 = new javax.swing.JLabel();
        answerLabel = new javax.swing.JLabel();
        doButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        derechosLabel = new javax.swing.JLabel();
        derechosEmailLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        dragLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeButton.setBackground(new java.awt.Color(0, 153, 153));
        minimizeButton.setFont(new java.awt.Font("Adobe Arabic", 0, 3)); // NOI18N
        minimizeButton.setForeground(new java.awt.Color(255, 255, 255));
        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize.png"))); // NOI18N
        minimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(minimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));

        labelTittle.setBackground(new java.awt.Color(79, 152, 43));
        labelTittle.setFont(new java.awt.Font("Gill Sans MT", 0, 28)); // NOI18N
        labelTittle.setText("StandarApp 2.3");
        getContentPane().add(labelTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 220, 40));

        instructionOne.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        instructionOne.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        instructionOne.setText("Indique la ruta del archivo de entrada");
        getContentPane().add(instructionOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 20));

        inFileTextField.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        inFileTextField.setText("Dirección del archivo de entrada...");
        getContentPane().add(inFileTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 240, 30));

        inFileButton.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        inFileButton.setText("jButton1");
        inFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inFileButtonActionPerformed(evt);
            }
        });
        getContentPane().add(inFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 30, 30));

        filaEncabezado1Label.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        filaEncabezado1Label.setText("Ingresar fila donde comienzan");
        getContentPane().add(filaEncabezado1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 210, 30));

        filaEncabezado2Label.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        filaEncabezado2Label.setText("los datos (SIN ENCABEZADO)");
        getContentPane().add(filaEncabezado2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 210, 30));

        fila_textField.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        fila_textField.setText("21");
        fila_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fila_textFieldActionPerformed(evt);
            }
        });
        getContentPane().add(fila_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 30, 30));

        especieLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        especieLabel.setText("especie");
        getContentPane().add(especieLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 60, 30));

        especie_textField.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        especie_textField.setText("19");
        especie_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especie_textFieldActionPerformed(evt);
            }
        });
        getContentPane().add(especie_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 30, 30));

        localidadLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        localidadLabel.setText("localidad");
        getContentPane().add(localidadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 70, 30));

        localidad_textField.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        localidad_textField.setText("17");
        localidad_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localidad_textFieldActionPerformed(evt);
            }
        });
        getContentPane().add(localidad_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 30, 30));

        fechaLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        fechaLabel.setText("fecha");
        getContentPane().add(fechaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 40, 30));

        fecha_textField.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        fecha_textField.setText("20");
        fecha_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha_textFieldActionPerformed(evt);
            }
        });
        getContentPane().add(fecha_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 30, 30));

        municipioLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        municipioLabel.setText("municipio");
        getContentPane().add(municipioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 80, 30));

        municipio_textField.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        municipio_textField.setText("16");
        municipio_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipio_textFieldActionPerformed(evt);
            }
        });
        getContentPane().add(municipio_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 30, 30));

        instructionFive.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        instructionFive.setText("Indique la ruta del archivo de salida");
        getContentPane().add(instructionFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 230, 20));

        outFileTextField.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        outFileTextField.setText("Ubicación para el archivo de salida...");
        getContentPane().add(outFileTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 240, 30));

        outFileButton.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        outFileButton.setText("jButton1");
        outFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outFileButtonActionPerformed(evt);
            }
        });
        getContentPane().add(outFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 30, 30));

        omitLabelThree.setFont(new java.awt.Font("Gill Sans MT", 0, 10)); // NOI18N
        omitLabelThree.setForeground(new java.awt.Color(51, 51, 51));
        omitLabelThree.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        omitLabelThree.setText("(Si desea sobreescribir el archivo de entrada");
        getContentPane().add(omitLabelThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        omitLabelThree1.setFont(new java.awt.Font("Gill Sans MT", 0, 10)); // NOI18N
        omitLabelThree1.setForeground(new java.awt.Color(51, 51, 51));
        omitLabelThree1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        omitLabelThree1.setText("ignore este paso, y presione arreglar)");
        getContentPane().add(omitLabelThree1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        answerLabel.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        answerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerLabel.setText("Presione arreglar para continuar");
        getContentPane().add(answerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 330, 20));

        doButton.setBackground(new java.awt.Color(0, 153, 153));
        doButton.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        doButton.setForeground(new java.awt.Color(255, 255, 255));
        doButton.setText("Arreglar");
        doButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doButtonActionPerformed(evt);
            }
        });
        getContentPane().add(doButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 110, -1));

        backButton.setBackground(new java.awt.Color(0, 153, 153));
        backButton.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Regresar");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 110, -1));

        exitButton.setBackground(new java.awt.Color(204, 51, 0));
        exitButton.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        exitButton.setText("Salir");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 70, -1));

        derechosLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        derechosLabel.setForeground(new java.awt.Color(153, 153, 153));
        derechosLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        derechosLabel.setText("Designed by Nicolas Ordoñez Chala, 2017");
        getContentPane().add(derechosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 260, 20));

        derechosEmailLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        derechosEmailLabel.setForeground(new java.awt.Color(153, 153, 153));
        derechosEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        derechosEmailLabel.setText("info: nordonezc@unal.edu.co");
        getContentPane().add(derechosEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 260, 20));

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SPicon.png"))); // NOI18N
        getContentPane().add(iconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 40));

        dragLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragLabelMouseDragged(evt);
            }
        });
        dragLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragLabelMousePressed(evt);
            }
        });
        getContentPane().add(dragLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 430));

        backgroundLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/greenPolygons.jpg"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doButtonActionPerformed
        // TODO add your handling code here:
        String nameIn = inFileTextField.getText();
        String nameOut = outFileTextField.getText();
        String collumns = municipio_textField.getText();
        int number1 = Integer.valueOf(municipio_textField.getText());
        int number2 = Integer.valueOf(localidad_textField.getText());
        int number3 = Integer.valueOf(especie_textField.getText());
        int number4 = Integer.valueOf(fecha_textField.getText());
        int number5 = Integer.valueOf(fila_textField.getText());
      
        try {
            if (!nameIn.contains("...")) {
                if (nameOut.contains("...")) {
                    System.out.println("Holi");
                    //String answer = rr.lectureRegistry(nameIn, nameIn);
                    answerLabel.setForeground(Color.BLUE);
                    //answerLabel.setText(answer + nameIn);

                } else if (Lecture.determineExtensionFile(nameIn)) {
                    //String answer = rr.lectureRegistry(nameIn, nameOut + "\\standarizedRegistries.xlsx", col, percent);
                    answerLabel.setForeground(Color.BLUE);
                    //answerLabel.setText(answer + " en: " + nameOut + "\\standarizedRegistries.xlsx");
                } else {
                    //String answer = rr.lectureRegistry(nameIn, nameOut + "\\standarizedRegistries.xls", col, percent);
                    answerLabel.setForeground(Color.BLUE);
                    //answerLabel.setText(answer + " en: " + nameOut + "\\fixedFile.xls");
                }
            } else {
                answerLabel.setForeground(Color.red);
                answerLabel.setText("No ha seleccionado ningun archivo");
            }
        } catch (Exception e) {
            answerLabel.setForeground(Color.red);
            answerLabel.setText("Revisar los campos de seleccion de archivos");
        }
    }//GEN-LAST:event_doButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu windowTwo = new Menu(this.getX(), this.getY());
        windowTwo.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void municipio_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipio_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipio_textFieldActionPerformed

    private void minimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeButtonActionPerformed
        // TODO add your handling code here:
        setState(this.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonActionPerformed

    private void dragLabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragLabelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_dragLabelMouseDragged

    private void dragLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragLabelMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_dragLabelMousePressed

    private void inFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inFileButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setFileFilter(new FileNameExtensionFilter("Excel Files", "xls", "xlsx"));
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("xls Files", "xls"));
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("xlsx Files", "xlsx"));
        chooser.setAcceptAllFileFilterUsed(false);
        
        int option = chooser.showOpenDialog(this);
        if (JFileChooser.CANCEL_OPTION == option) 
            inFileTextField.setText("No ha seleccionado ningun archivo...");
        
        if (JFileChooser.APPROVE_OPTION == option) 
            inFileTextField.setText(chooser.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_inFileButtonActionPerformed

    private void outFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outFileButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        int option = chooser.showSaveDialog(this);
        if (JFileChooser.APPROVE_OPTION == option) 
            outFileTextField.setText("No ha seleccionado ninguna ubicación...");
        
        if (JFileChooser.APPROVE_OPTION == option) 
            outFileTextField.setText(chooser.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_outFileButtonActionPerformed

    private void localidad_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localidad_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localidad_textFieldActionPerformed

    private void especie_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especie_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especie_textFieldActionPerformed

    private void fila_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fila_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fila_textFieldActionPerformed

    private void fecha_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha_textFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answerLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel derechosEmailLabel;
    private javax.swing.JLabel derechosLabel;
    private javax.swing.JButton doButton;
    private javax.swing.JLabel dragLabel;
    private javax.swing.JLabel especieLabel;
    private javax.swing.JTextField especie_textField;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JTextField fecha_textField;
    private javax.swing.JLabel filaEncabezado1Label;
    private javax.swing.JLabel filaEncabezado2Label;
    private javax.swing.JTextField fila_textField;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JButton inFileButton;
    private javax.swing.JTextField inFileTextField;
    private javax.swing.JLabel instructionFive;
    private javax.swing.JLabel instructionOne;
    private javax.swing.JLabel labelTittle;
    private javax.swing.JLabel localidadLabel;
    private javax.swing.JTextField localidad_textField;
    private javax.swing.JButton minimizeButton;
    private javax.swing.JLabel municipioLabel;
    private javax.swing.JTextField municipio_textField;
    private javax.swing.JLabel omitLabelThree;
    private javax.swing.JLabel omitLabelThree1;
    private javax.swing.JButton outFileButton;
    private javax.swing.JTextField outFileTextField;
    // End of variables declaration//GEN-END:variables
}
